# Generated by Django 3.2.8 on 2021-10-17 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pontoturistico_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='enderecos',
            new_name='endereco',
        ),
    ]
